### ISSUE TITLE
Update Release List fails

### ISSUE THREAD

**Issue by chrisbra** [vim/vim-win32-installer#267]
### Steps to reproduce

This happened yesterday: 

https://github.com/vim/vim-win32-installer/runs/6870630744?check_suite_focus=true
```
The latest release in the list: v8.2.5076
Traceback (most recent call last):
  File "../main/scripts/update-release-list.py", line 124, in <module>
    main()
  File "../main/scripts/update-release-list.py", line 120, in main
    write_new_rels(new_rels, latest_rel)
  File "../main/scripts/update-release-list.py", line 83, in write_new_rels
    y = rel['published_at'][:4]
TypeError: 'NoneType' object is not subscriptable
New releases: v8.2.5085
Error: Process completed with exit code 1.
```

ping @k-takata 

### Expected behaviour

 no error

### Version of Vim

v8.2.5076

### Environment

Github Actions

**Comment by k-takata** [comment]
I reran it and it didn't fail. Not sure why.

**Comment by k-takata** [comment]
Timing issue?
